/*
===========================================================================
sv_bot_bridge.c - Python AI Bridge for Quake3e

Non-blocking TCP socket server that streams game state to Python clients
and receives bot commands back.

Protocol: line-delimited JSON (\n terminated)
  -> To Python:   {"type":"state", "time":12345, "entities":[...], "events":[...]}
  -> From Python:  {"type":"cmd", "client":0, "move":[1,0,0], "speed":400, ...}
===========================================================================
*/

#include "server.h"
#include "../botlib/botlib.h"
#include "sv_bot_bridge.h"

#include <math.h>

// FlatBuffers wire protocol (replaces line-delimited JSON). Generated by flatcc from
// code/flatcc/bridge.fbs; runtime + generated header vendored under code/flatcc/
// (include paths added in CMakeLists). The Python side is generated from the same
// schema (flatc --python). See code/flatcc/README.md.
#include "bridge_generated.h"

#ifdef _WIN32
#include <winsock2.h>
#include <ws2tcpip.h>
typedef SOCKET socket_t;
#define INVALID_SOCK INVALID_SOCKET
#define SOCK_ERROR   SOCKET_ERROR
#define BRIDGE_CLOSE closesocket
#define BRIDGE_IOCTL ioctlsocket
#else
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <signal.h>
typedef int socket_t;
#define INVALID_SOCK (-1)
#define SOCK_ERROR   (-1)
#define BRIDGE_CLOSE close
#endif

// ============================================================================
// Bridge state
// ============================================================================

typedef struct {
    socket_t    sock;
    qboolean    active;
    qboolean    isAI;           // true = AI controller, false = monitor only
    int         controlledBot;  // clientNum this AI controls (-1 = monitor)
    char        *recvBuf;       // dynamically allocated [BRIDGE_BUFFER_SIZE]
    int         recvLen;
} bridge_client_t;

static struct {
    qboolean        initialized;
    socket_t        listenSock;
    bridge_client_t clients[BRIDGE_MAX_CLIENTS];
    int             numClients;

    // Entity state snapshot for current frame (enriched with playerState data)
    bridge_entity_t     *entities;          // dynamically allocated [BRIDGE_MAX_ENTITIES]
    qboolean            *entityUpdated;     // dynamically allocated [BRIDGE_MAX_ENTITIES]
    int                 numEntities;

    // Events queued this frame
    bridge_event_t  events[BRIDGE_MAX_EVENTS_PER_FRAME];
    int             numEvents;

    // Bot commands received from Python
    bridge_bot_cmd_t    botCmds[MAX_CLIENTS];
    qboolean            botCmdValid[MAX_CLIENTS];

    cvar_t  *port;
    cvar_t  *enabled;
    cvar_t  *fullstate;     // 1 = emit every active client each frame (see SV_BridgeRefreshActiveClients)
} bridge;

// ============================================================================
// Socket helpers
// ============================================================================

static void Bridge_SetNonBlocking( socket_t sock ) {
#ifdef _WIN32
    u_long mode = 1;
    BRIDGE_IOCTL( sock, FIONBIO, &mode );
#else
    int flags = fcntl( sock, F_GETFL, 0 );
    fcntl( sock, F_SETFL, flags | O_NONBLOCK );
#endif
}

static void Bridge_SetNoDelay( socket_t sock ) {
    int flag = 1;
    setsockopt( sock, IPPROTO_TCP, TCP_NODELAY, (const char*)&flag, sizeof(flag) );
}

// ============================================================================
// JSON helpers (minimal, no external dependency)
// ============================================================================

// Truncating sprintf that returns chars written
static int Com_sprintf_truncated( char *buf, int maxlen, const char *fmt, ... ) {
    va_list ap;
    int len;
    va_start( ap, fmt );
    len = Q_vsnprintf( buf, maxlen, fmt, ap );
    va_end( ap );
    if ( len >= maxlen ) len = maxlen - 1;
    if ( len < 0 ) len = 0;
    return len;
}

static int Bridge_WriteVec3( char *buf, int maxlen, const char *key, vec3_t v ) {
    return Com_sprintf_truncated( buf, maxlen, "\"%s\":[%.2f,%.2f,%.2f]", key, v[0], v[1], v[2] );
}

// ============================================================================
// Geometric distance sensors (engine-side raycasts). Box-trace the player hull
// against the WORLD collision model (exact walls, bodies excluded) along a fixed
// fan of bearings. Bearings MUST match obs_action_spec.py (WALL_FRONT/WALL_SIDE
// view-relative, VEL_CLUSTER velocity-relative). Sends RAW distances (units);
// Python normalises to proximity = 1 - min(d,R)/R. Purely read-only (no game-state
// change); computed only while building a frame, i.e. only when a client is
// connected. See Bot_Python_IA/docs/generalisation_transfert.md section 6.
// ============================================================================
#define BRIDGE_SENSOR_N_ARC   13   // wall_front(7) + wall_side(6), view-relative
#define BRIDGE_SENSOR_N_VEL   3    // vel_lookahead cluster, velocity-relative
#define BRIDGE_SENSOR_N_RAY   (BRIDGE_SENSOR_N_ARC + BRIDGE_SENSOR_N_VEL)  // 16
#define BRIDGE_SENSOR_RANGE_U 2048.0f
#define BRIDGE_SENSOR_RANGE_V 512.0f
// world walls the player collides with, EXCLUDING bodies (other bots aren't walls).
#define BRIDGE_WALL_MASK      (CONTENTS_SOLID | CONTENTS_PLAYERCLIP)

static const float bridge_arc_deg[BRIDGE_SENSOR_N_ARC] = {
    -67.5f, -45.0f, -22.5f, 0.0f, 22.5f, 45.0f, 67.5f,       // wall_front (vs view yaw)
    -135.0f, -112.5f, -90.0f, 90.0f, 112.5f, 135.0f          // wall_side  (vs view yaw)
};
static const float bridge_vel_deg[BRIDGE_SENSOR_N_VEL] = { -20.0f, 0.0f, 20.0f };

// Horizontal box-trace of the player hull from `start` along world bearing `deg`.
static float Bridge_TraceDist( const vec3_t start, float deg, float range ) {
    static const vec3_t pmins = { -15.0f, -15.0f, -24.0f };  // standard player hull
    static const vec3_t pmaxs = {  15.0f,  15.0f,  32.0f };
    float rad = DEG2RAD( deg );
    vec3_t end;
    trace_t tr;
    end[0] = start[0] + cosf( rad ) * range;
    end[1] = start[1] + sinf( rad ) * range;
    end[2] = start[2];
    CM_BoxTrace( &tr, start, end, pmins, pmaxs, 0, BRIDGE_WALL_MASK, qfalse );
    return tr.fraction * range;
}

// Vertical point-trace (dz = +-range) -> distance to ground/ceiling; SURF_SLICK out.
static float Bridge_TraceVert( const vec3_t start, float dz, int *slickOut ) {
    static const vec3_t zero = { 0.0f, 0.0f, 0.0f };
    vec3_t end;
    trace_t tr;
    VectorCopy( start, end );
    end[2] += dz;
    CM_BoxTrace( &tr, start, end, zero, zero, 0, BRIDGE_WALL_MASK, qfalse );
    if ( slickOut )
        *slickOut = ( tr.fraction < 1.0f && ( tr.surfaceFlags & SURF_SLICK ) ) ? 1 : 0;
    return tr.fraction * ( dz < 0 ? -dz : dz );
}

// Fill the 16 ray distances (view-arc then velocity-cluster) + ground/ceiling + slick.
static void Bridge_ComputeSensors( bridge_entity_t *ent, float *rays, float *ground,
                                   float *ceiling, int *slick ) {
    float yaw = ent->viewangles[YAW];
    float vh  = sqrtf( ent->velocity[0]*ent->velocity[0] + ent->velocity[1]*ent->velocity[1] );
    // velocity heading; fall back to the view when ~stationary (matches raycast.py).
    float velyaw = ( vh > 1.0f )
        ? RAD2DEG( atan2f( ent->velocity[1], ent->velocity[0] ) ) : yaw;
    int k;
    for ( k = 0; k < BRIDGE_SENSOR_N_ARC; k++ )
        rays[k] = Bridge_TraceDist( ent->base.origin, yaw + bridge_arc_deg[k],
                                    BRIDGE_SENSOR_RANGE_U );
    for ( k = 0; k < BRIDGE_SENSOR_N_VEL; k++ )
        rays[BRIDGE_SENSOR_N_ARC + k] = Bridge_TraceDist(
            ent->base.origin, velyaw + bridge_vel_deg[k], BRIDGE_SENSOR_RANGE_U );
    *ground  = Bridge_TraceVert( ent->base.origin, -BRIDGE_SENSOR_RANGE_V, slick );
    *ceiling = Bridge_TraceVert( ent->base.origin,  BRIDGE_SENSOR_RANGE_V, NULL );
}

// ============================================================================
// FlatBuffers builder (single, reused each frame — the bridge is single-threaded)
// + length-prefixed framing (4-byte little-endian length + the FlatBuffer).
// ============================================================================
static flatcc_builder_t g_fbb;
static qboolean         g_fbb_ready = qfalse;

static flatcc_builder_t *Bridge_Builder( void ) {
    if ( !g_fbb_ready ) { flatcc_builder_init( &g_fbb ); g_fbb_ready = qtrue; }
    else                { flatcc_builder_reset( &g_fbb ); }
    return &g_fbb;
}

// Copy the finalized FlatBuffer into `out` behind a 4-byte LE length prefix.
// Returns the framed length, or 0 if it does not fit in `cap`.
static int Bridge_FrameBuffer( flatcc_builder_t *B, char *out, int cap ) {
    size_t sz = flatcc_builder_get_buffer_size( B );
    if ( (int)sz + 4 > cap || sz == 0 ) return 0;
    out[0] = (char)(  sz         & 0xff );
    out[1] = (char)( (sz >> 8)   & 0xff );
    out[2] = (char)( (sz >> 16)  & 0xff );
    out[3] = (char)( (sz >> 24)  & 0xff );
    flatcc_builder_copy_buffer( B, out + 4, sz );
    return (int)sz + 4;
}

static int Bridge_WriteEntityJson( char *buf, int maxlen, int entNum, bridge_entity_t *ent ) {
    int len = 0;
    int n;
    bot_entitystate_t *b = &ent->base;

    n = Com_sprintf_truncated( buf + len, maxlen - len,
        "{\"id\":%d,\"type\":%d,\"flags\":%d,",
        entNum, b->type, b->flags );
    len += n;

    n = Bridge_WriteVec3( buf + len, maxlen - len, "origin", b->origin );
    len += n;

    n = Com_sprintf_truncated( buf + len, maxlen - len, "," );
    len += n;

    n = Bridge_WriteVec3( buf + len, maxlen - len, "velocity", ent->velocity );
    len += n;

    n = Com_sprintf_truncated( buf + len, maxlen - len, "," );
    len += n;

    n = Bridge_WriteVec3( buf + len, maxlen - len, "angles", b->angles );
    len += n;

    n = Com_sprintf_truncated( buf + len, maxlen - len, "," );
    len += n;

    n = Bridge_WriteVec3( buf + len, maxlen - len, "viewangles", ent->viewangles );
    len += n;

    n = Com_sprintf_truncated( buf + len, maxlen - len,
        ",\"health\":%d,\"armor\":%d,\"weapon\":%d,\"ammo\":%d,"
        "\"clientNum\":%d,\"groundent\":%d,\"event\":%d,\"eventParm\":%d,"
        "\"powerups\":%d,\"modelindex\":%d,\"modelindex2\":%d,"
        "\"legsAnim\":%d,\"torsoAnim\":%d",
        ent->health, ent->armor, b->weapon, ent->ammo,
        ent->clientNum, b->groundent, b->event, b->eventParm,
        b->powerups, b->modelindex, b->modelindex2,
        b->legsAnim, b->torsoAnim );
    len += n;

    // Geometric distance sensors (raw units; Python normalises to proximity).
    {
        float rays[BRIDGE_SENSOR_N_RAY], ground, ceiling;
        int   slick, r;
        Bridge_ComputeSensors( ent, rays, &ground, &ceiling, &slick );
        n = Com_sprintf_truncated( buf + len, maxlen - len, ",\"rays\":[" );
        len += n;
        for ( r = 0; r < BRIDGE_SENSOR_N_RAY; r++ ) {
            n = Com_sprintf_truncated( buf + len, maxlen - len,
                r ? ",%.1f" : "%.1f", rays[r] );
            len += n;
        }
        n = Com_sprintf_truncated( buf + len, maxlen - len,
            "],\"ground\":%.1f,\"ceiling\":%.1f,\"slick\":%d}", ground, ceiling, slick );
        len += n;
    }

    return len;
}

static int Bridge_WriteEventJson( char *buf, int maxlen, bridge_event_t *evt ) {
    int len = 0;
    int n;

    n = Com_sprintf_truncated( buf + len, maxlen - len,
        "{\"type\":%d,\"time\":%d,\"ent\":%d,\"other\":%d,\"value\":%d,",
        evt->type, evt->serverTime, evt->entityNum, evt->otherEntityNum, evt->value );
    len += n;

    n = Bridge_WriteVec3( buf + len, maxlen - len, "origin", evt->origin );
    len += n;

    n = Com_sprintf_truncated( buf + len, maxlen - len, "}" );
    len += n;

    return len;
}

// ============================================================================
// JSON parsing (minimal for bot commands)
// ============================================================================

static float Bridge_ParseFloat( const char *json, const char *key, float defaultVal ) {
    char search[64];
    const char *p;

    Com_sprintf( search, sizeof(search), "\"%s\":", key );
    p = strstr( json, search );
    if ( !p ) return defaultVal;
    p += strlen( search );
    while ( *p == ' ' ) p++;
    return (float)atof( p );
}

static int Bridge_ParseInt( const char *json, const char *key, int defaultVal ) {
    char search[64];
    const char *p;

    Com_sprintf( search, sizeof(search), "\"%s\":", key );
    p = strstr( json, search );
    if ( !p ) return defaultVal;
    p += strlen( search );
    while ( *p == ' ' ) p++;
    return atoi( p );
}

static void Bridge_ParseVec3( const char *json, const char *key, vec3_t out ) {
    char search[64];
    const char *p;

    // Try compact format "key":[  then spaced format "key": [
    Com_sprintf( search, sizeof(search), "\"%s\":[", key );
    p = strstr( json, search );
    if ( !p ) {
        Com_sprintf( search, sizeof(search), "\"%s\": [", key );
        p = strstr( json, search );
    }
    if ( !p ) {
        VectorClear( out );
        return;
    }
    p += strlen( search );
    out[0] = (float)atof( p );
    p = strchr( p, ',' );
    if ( !p ) return;
    out[1] = (float)atof( p + 1 );
    p = strchr( p + 1, ',' );
    if ( !p ) return;
    out[2] = (float)atof( p + 1 );
}

static void Bridge_ProcessCommand( const char *json ) {
    int clientNum;
    bridge_bot_cmd_t *cmd;

    clientNum = Bridge_ParseInt( json, "client", -1 );
    if ( clientNum < 0 || clientNum >= sv_maxclients->integer ) return;

    cmd = &bridge.botCmds[clientNum];

    Bridge_ParseVec3( json, "move", cmd->moveDir );
    cmd->moveSpeed  = Bridge_ParseFloat( json, "speed", 0.0f );
    Bridge_ParseVec3( json, "view", cmd->viewAngles );
    cmd->attack     = Bridge_ParseInt( json, "attack", 0 );
    cmd->jump       = Bridge_ParseInt( json, "jump", 0 );
    cmd->crouch     = Bridge_ParseInt( json, "crouch", 0 );
    cmd->sprint     = Bridge_ParseInt( json, "sprint", 0 );
    cmd->use        = Bridge_ParseInt( json, "use", 0 );
    cmd->weapon     = Bridge_ParseInt( json, "weapon", 0 );
    cmd->respawn    = Bridge_ParseInt( json, "respawn", 0 );
    cmd->clientNum  = clientNum;

    bridge.botCmdValid[clientNum] = qtrue;

    // Debug: log first received command per bot
    {
        static int cmdRecvCount[MAX_CLIENTS] = {0};
        cmdRecvCount[clientNum]++;
        if ( cmdRecvCount[clientNum] <= 3 || cmdRecvCount[clientNum] % 500 == 0 ) {
            Com_DPrintf( "Bridge DEBUG: received cmd #%d for bot %d: "
                "move=(%.2f,%.2f,%.2f) speed=%.0f view=(%.1f,%.1f,%.1f)\n",
                cmdRecvCount[clientNum], clientNum,
                cmd->moveDir[0], cmd->moveDir[1], cmd->moveDir[2],
                cmd->moveSpeed,
                cmd->viewAngles[0], cmd->viewAngles[1], cmd->viewAngles[2] );
        }
    }
}

// ============================================================================
// Network I/O
// ============================================================================

// Parse one received FlatBuffers Message frame (Register or Command) and apply it.
static void Bridge_ProcessFrame( bridge_client_t *cl, int clIdx, const void *buf, int size ) {
    UrtBridge_Message_table_t msg;

    if ( UrtBridge_Message_verify_as_root( buf, (size_t)size ) ) return;  // malformed -> drop
    msg = UrtBridge_Message_as_root( buf );

    switch ( UrtBridge_Message_payload_type( msg ) ) {
    case UrtBridge_Payload_Register: {
        UrtBridge_Register_table_t r = (UrtBridge_Register_table_t) UrtBridge_Message_payload( msg );
        int botNum = UrtBridge_Register_bot( r );
        if ( UrtBridge_Register_is_ai( r ) && botNum >= 0 && botNum < sv_maxclients->integer ) {
            cl->isAI = qtrue;
            cl->controlledBot = botNum;
            Com_Printf( "Bridge: client %d registered as AI for bot %d\n", clIdx, botNum );
        } else {
            cl->isAI = qfalse;
            cl->controlledBot = -1;
            Com_Printf( "Bridge: client %d registered as monitor\n", clIdx );
        }
        break;
    }
    case UrtBridge_Payload_Command: {
        UrtBridge_Command_table_t c;
        UrtBridge_Vec3_struct_t mv, vw;
        bridge_bot_cmd_t *cmd;
        int clientNum;

        if ( !cl->isAI ) break;
        c = (UrtBridge_Command_table_t) UrtBridge_Message_payload( msg );
        clientNum = UrtBridge_Command_client( c );
        if ( clientNum < 0 || clientNum >= sv_maxclients->integer ) break;

        cmd = &bridge.botCmds[clientNum];
        mv = UrtBridge_Command_move( c );
        vw = UrtBridge_Command_view( c );
        if ( mv ) { cmd->moveDir[0] = UrtBridge_Vec3_x(mv); cmd->moveDir[1] = UrtBridge_Vec3_y(mv); cmd->moveDir[2] = UrtBridge_Vec3_z(mv); }
        if ( vw ) { cmd->viewAngles[0] = UrtBridge_Vec3_x(vw); cmd->viewAngles[1] = UrtBridge_Vec3_y(vw); cmd->viewAngles[2] = UrtBridge_Vec3_z(vw); }
        cmd->moveSpeed = UrtBridge_Command_speed( c );
        cmd->attack    = UrtBridge_Command_attack( c );
        cmd->jump      = UrtBridge_Command_jump( c );
        cmd->crouch    = UrtBridge_Command_crouch( c );
        cmd->sprint    = UrtBridge_Command_sprint( c );
        cmd->use       = UrtBridge_Command_use( c );
        cmd->weapon    = UrtBridge_Command_weapon( c );
        cmd->respawn   = UrtBridge_Command_respawn( c );
        cmd->clientNum = clientNum;
        bridge.botCmdValid[clientNum] = qtrue;
        break;
    }
    default:
        break;
    }
}

static void Bridge_AcceptClients( void ) {
    struct sockaddr_in addr;
    socklen_t addrLen = sizeof(addr);
    socket_t newSock;
    int i;

    newSock = accept( bridge.listenSock, (struct sockaddr*)&addr, &addrLen );
    if ( newSock == INVALID_SOCK ) return;

    // Find free slot
    for ( i = 0; i < BRIDGE_MAX_CLIENTS; i++ ) {
        if ( !bridge.clients[i].active ) break;
    }

    if ( i == BRIDGE_MAX_CLIENTS ) {
        Com_Printf( S_COLOR_YELLOW "Bridge: max clients reached, rejecting connection\n" );
        BRIDGE_CLOSE( newSock );
        return;
    }

    Bridge_SetNonBlocking( newSock );
    Bridge_SetNoDelay( newSock );

    bridge.clients[i].sock = newSock;
    bridge.clients[i].active = qtrue;
    bridge.clients[i].isAI = qfalse;
    bridge.clients[i].controlledBot = -1;
    bridge.clients[i].recvLen = 0;
    bridge.numClients++;

    Com_Printf( "Bridge: client %d connected from %s\n", i, inet_ntoa(addr.sin_addr) );
}

static void Bridge_DisconnectClient( int idx ) {
    if ( !bridge.clients[idx].active ) return;

    BRIDGE_CLOSE( bridge.clients[idx].sock );
    bridge.clients[idx].active = qfalse;
    bridge.clients[idx].sock = INVALID_SOCK;

    // Clear bot command if this AI was controlling a bot
    if ( bridge.clients[idx].controlledBot >= 0 ) {
        bridge.botCmdValid[ bridge.clients[idx].controlledBot ] = qfalse;
    }

    bridge.clients[idx].controlledBot = -1;
    bridge.numClients--;

    Com_Printf( "Bridge: client %d disconnected\n", idx );
}

static void Bridge_ReceiveData( void ) {
    int i;

    for ( i = 0; i < BRIDGE_MAX_CLIENTS; i++ ) {
        bridge_client_t *cl = &bridge.clients[i];
        int bytesRead;

        if ( !cl->active ) continue;

        // Read available data
        bytesRead = recv( cl->sock, cl->recvBuf + cl->recvLen,
                          BRIDGE_BUFFER_SIZE - cl->recvLen - 1, 0 );

        if ( bytesRead == 0 ) {
            Bridge_DisconnectClient( i );
            continue;
        }

        if ( bytesRead > 0 ) {
            int off = 0;
            cl->recvLen += bytesRead;

            // Process complete length-prefixed FlatBuffers frames
            while ( cl->recvLen - off >= 4 ) {
                unsigned char *p = (unsigned char *)( cl->recvBuf + off );
                int flen = p[0] | (p[1] << 8) | (p[2] << 16) | ((int)p[3] << 24);
                if ( flen < 0 || flen > BRIDGE_BUFFER_SIZE ) { off = cl->recvLen; break; }  // corrupt
                if ( cl->recvLen - off - 4 < flen ) break;                                  // partial frame
                Bridge_ProcessFrame( cl, i, cl->recvBuf + off + 4, flen );
                off += 4 + flen;
            }
            if ( off > 0 ) {
                cl->recvLen -= off;
                if ( cl->recvLen > 0 ) memmove( cl->recvBuf, cl->recvBuf + off, cl->recvLen );
            }

            // Prevent buffer overflow (a frame larger than the buffer is dropped)
            if ( cl->recvLen >= BRIDGE_BUFFER_SIZE - 1 ) {
                cl->recvLen = 0;
            }
        }
    }
}

static void Bridge_SendToAll( const char *data, int len ) {
    int i;

    for ( i = 0; i < BRIDGE_MAX_CLIENTS; i++ ) {
        if ( !bridge.clients[i].active ) continue;

        {
            int flags = 0;
#ifndef _WIN32
            flags = MSG_NOSIGNAL;  // prevent SIGPIPE on broken connection
#endif
            if ( send( bridge.clients[i].sock, data, len, flags ) == SOCK_ERROR ) {
#ifdef _WIN32
                if ( WSAGetLastError() != WSAEWOULDBLOCK ) {
#else
                if ( errno != EAGAIN && errno != EWOULDBLOCK ) {
#endif
                    Bridge_DisconnectClient( i );
                }
            }
        }
    }
}

// Per-frame game STATE is consumed only by MONITOR clients (the training loop
// reads every bot's observation from ONE monitor connection). AI clients are
// send-only: streaming the full state to each was pure overhead — N redundant
// engine-side copies, N Python recv threads draining+discarding it, and a
// socket backlog that floods every core the instant the trainer pauses the
// collect loop for a PPO update. Emitting to monitors only removes all of that.
// (game_init still uses Bridge_SendToAll — rare, and AI clients simply ignore
// it.) Functional only: no gameplay/physics/think change.
static void Bridge_SendToMonitors( const char *data, int len ) {
    int i;

    for ( i = 0; i < BRIDGE_MAX_CLIENTS; i++ ) {
        if ( !bridge.clients[i].active ) continue;
        if ( bridge.clients[i].isAI ) continue;   // AI = send-only, ignores state

        {
            int flags = 0;
#ifndef _WIN32
            flags = MSG_NOSIGNAL;  // prevent SIGPIPE on broken connection
#endif
            if ( send( bridge.clients[i].sock, data, len, flags ) == SOCK_ERROR ) {
#ifdef _WIN32
                if ( WSAGetLastError() != WSAEWOULDBLOCK ) {
#else
                if ( errno != EAGAIN && errno != EWOULDBLOCK ) {
#endif
                    Bridge_DisconnectClient( i );
                }
            }
        }
    }
}

// ============================================================================
// Public API
// ============================================================================

// Notify Python bridge clients that a GAME_INIT (map load / map_restart) just
// happened. The QVM (G_InitGame) resets some cvars at every init (e.g. g_stamina);
// the backend re-applies them from conf/q3 over RCON on this signal.
void SV_BridgeBroadcastGameInit( void ) {
    static char buf[128];
    flatcc_builder_t *B;
    UrtBridge_GameInit_ref_t gi;
    int n;

    if ( !bridge.initialized ) {
        return;
    }
    B = Bridge_Builder();
    UrtBridge_GameInit_start( B );
    gi = UrtBridge_GameInit_end( B );
    UrtBridge_Message_create_as_root( B, UrtBridge_Payload_as_GameInit( gi ) );
    n = Bridge_FrameBuffer( B, buf, sizeof( buf ) );
    if ( n > 0 ) Bridge_SendToAll( buf, n );
}

void SV_BridgeInit( void ) {
    struct sockaddr_in addr;
    int opt = 1;
    int i;

    // If the bridge is already running (map_restart), keep the listen socket
    // and all client connections alive — only reset per-frame entity state.
    if ( bridge.initialized && bridge.listenSock != INVALID_SOCK ) {
        Com_Printf( "Bridge: map restart — keeping listen socket and %d client(s)\n",
                     bridge.numClients );

        // Reset entity state for the new map
        if ( bridge.entities ) {
            Com_Memset( bridge.entities, 0, BRIDGE_MAX_ENTITIES * sizeof(bridge_entity_t) );
        }
        if ( bridge.entityUpdated ) {
            Com_Memset( bridge.entityUpdated, 0, BRIDGE_MAX_ENTITIES * sizeof(qboolean) );
        }
        bridge.numEntities = 0;
        bridge.numEvents = 0;

        // Clear pending bot commands (clients will re-send)
        Com_Memset( bridge.botCmds, 0, sizeof(bridge.botCmds) );
        Com_Memset( bridge.botCmdValid, 0, sizeof(bridge.botCmdValid) );

        return;
    }

    Com_Memset( &bridge, 0, sizeof(bridge) );
    bridge.listenSock = INVALID_SOCK;

    bridge.enabled = Cvar_Get( "bridge_enabled", "0", 0 );
    bridge.port = Cvar_Get( "bridge_port", va("%d", BRIDGE_DEFAULT_PORT), CVAR_ARCHIVE );
    // 1 = engine emits every active client's fresh kinematics each server frame
    // (decouples observation rate from the QVM's ~10 Hz entity push). See piège 22.
    bridge.fullstate = Cvar_Get( "bridge_fullstate", "1", 0 );

    if ( !bridge.enabled->integer ) {
        Com_Printf( "Bridge: disabled (set bridge_enabled 1 to enable)\n" );
        return;
    }

    // Allocate dynamic arrays
    bridge.entities = (bridge_entity_t *) Z_Malloc( BRIDGE_MAX_ENTITIES * sizeof(bridge_entity_t) );
    bridge.entityUpdated = (qboolean *) Z_Malloc( BRIDGE_MAX_ENTITIES * sizeof(qboolean) );
    Com_Memset( bridge.entities, 0, BRIDGE_MAX_ENTITIES * sizeof(bridge_entity_t) );
    Com_Memset( bridge.entityUpdated, 0, BRIDGE_MAX_ENTITIES * sizeof(qboolean) );

    // Allocate client receive buffers
    for ( i = 0; i < BRIDGE_MAX_CLIENTS; i++ ) {
        bridge.clients[i].recvBuf = (char *) Z_Malloc( BRIDGE_BUFFER_SIZE );
        bridge.clients[i].recvBuf[0] = '\0';
    }

#ifdef _WIN32
    {
        WSADATA wsaData;
        if ( WSAStartup( MAKEWORD(2,2), &wsaData ) != 0 ) {
            Com_Printf( S_COLOR_RED "Bridge: WSAStartup failed\n" );
            return;
        }
    }
#endif

#ifndef _WIN32
    // Ignore SIGPIPE so writing to a disconnected client doesn't kill the server
    signal( SIGPIPE, SIG_IGN );
#endif

    bridge.listenSock = socket( AF_INET, SOCK_STREAM, IPPROTO_TCP );
    if ( bridge.listenSock == INVALID_SOCK ) {
        Com_Printf( S_COLOR_RED "Bridge: failed to create socket\n" );
        return;
    }

    setsockopt( bridge.listenSock, SOL_SOCKET, SO_REUSEADDR, (const char*)&opt, sizeof(opt) );
    Bridge_SetNonBlocking( bridge.listenSock );

    Com_Memset( &addr, 0, sizeof(addr) );
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = htonl( INADDR_ANY );
    addr.sin_port = htons( (unsigned short)bridge.port->integer );

    if ( bind( bridge.listenSock, (struct sockaddr*)&addr, sizeof(addr) ) == SOCK_ERROR ) {
        Com_Printf( S_COLOR_RED "Bridge: bind failed on port %d\n", bridge.port->integer );
        BRIDGE_CLOSE( bridge.listenSock );
        bridge.listenSock = INVALID_SOCK;
        return;
    }

    if ( listen( bridge.listenSock, BRIDGE_MAX_CLIENTS ) == SOCK_ERROR ) {
        Com_Printf( S_COLOR_RED "Bridge: listen failed\n" );
        BRIDGE_CLOSE( bridge.listenSock );
        bridge.listenSock = INVALID_SOCK;
        return;
    }

    bridge.initialized = qtrue;
    Com_Printf( "Bridge: listening on port %d (Python AI bot & monitoring)\n", bridge.port->integer );
    Com_Printf( "Bridge: waiting for connections...\n" );
    Com_Printf( "Bridge:   - Bot AI:     connect and send {\"type\":\"register\",\"bot\":N}\n" );
    Com_Printf( "Bridge:   - Monitor:    connect and send {\"type\":\"register\"}\n" );
}

void SV_BridgeShutdown( void ) {
    if ( !bridge.initialized ) return;

    // On map_restart, SV_BotLibShutdown is called followed by SV_BotInitBotLib.
    // We keep the bridge alive so clients don't lose their connections.
    // SV_BridgeInit will detect the live bridge and skip re-creation.
    // SV_BridgeForceShutdown is called from SV_Shutdown for a real server quit.
    Com_Printf( "Bridge: keeping alive across map restart (%d client(s) connected)\n",
                 bridge.numClients );
}

void SV_BridgeForceShutdown( void ) {
    int i;

    if ( !bridge.initialized ) return;

    Com_Printf( "Bridge: full shutdown\n" );

    if ( g_fbb_ready ) {
        flatcc_builder_clear( &g_fbb );
        g_fbb_ready = qfalse;
    }

    for ( i = 0; i < BRIDGE_MAX_CLIENTS; i++ ) {
        if ( bridge.clients[i].active ) {
            Bridge_DisconnectClient( i );
        }
    }

    if ( bridge.listenSock != INVALID_SOCK ) {
        BRIDGE_CLOSE( bridge.listenSock );
        bridge.listenSock = INVALID_SOCK;
    }

#ifdef _WIN32
    WSACleanup();
#endif

    // Free dynamic arrays
    if ( bridge.entities ) {
        Z_Free( bridge.entities );
        bridge.entities = NULL;
    }
    if ( bridge.entityUpdated ) {
        Z_Free( bridge.entityUpdated );
        bridge.entityUpdated = NULL;
    }
    for ( i = 0; i < BRIDGE_MAX_CLIENTS; i++ ) {
        if ( bridge.clients[i].recvBuf ) {
            Z_Free( bridge.clients[i].recvBuf );
            bridge.clients[i].recvBuf = NULL;
        }
    }

    bridge.initialized = qfalse;
}

void SV_BridgeUpdateEntity( int entNum, bot_entitystate_t *state ) {
    bridge_entity_t *bent;

    if ( !bridge.initialized ) return;
    if ( !state ) return;
    if ( !bridge.entities || !bridge.entityUpdated ) return;
    if ( entNum < 0 || entNum >= BRIDGE_MAX_ENTITIES ) return;

    bent = &bridge.entities[entNum];

    // Copy the base entity state (QVM-safe, original struct size)
    Com_Memcpy( &bent->base, state, sizeof(bot_entitystate_t) );

    // Enrich with playerState_t data if this is a client entity
    if ( sv_maxclients && entNum >= 0 && entNum < sv_maxclients->integer && sv.gameClients ) {
        playerState_t *ps = SV_GameClientNum( entNum );
        if ( ps ) {
            VectorCopy( ps->velocity, bent->velocity );
            bent->health = ps->stats[0];    // STAT_HEALTH
            bent->armor = ps->stats[3];      // STAT_ARMOR
            bent->clientNum = ps->clientNum;
            if ( ps->weapon >= 0 && ps->weapon < MAX_WEAPONS ) {
                bent->ammo = ps->ammo[ps->weapon];
            } else {
                bent->ammo = 0;
            }
            VectorCopy( ps->viewangles, bent->viewangles );
        } else {
            VectorClear( bent->velocity );
            bent->health = 0;
            bent->armor = 0;
            bent->clientNum = entNum;
            bent->ammo = 0;
            VectorClear( bent->viewangles );
        }
    } else {
        VectorClear( bent->velocity );
        bent->health = 0;
        bent->armor = 0;
        bent->clientNum = -1;
        bent->ammo = 0;
        VectorClear( bent->viewangles );
    }

    bridge.entityUpdated[entNum] = qtrue;
    if ( entNum >= bridge.numEntities ) {
        bridge.numEntities = entNum + 1;
    }
}

void SV_BridgePushEvent( bridge_event_t *event ) {
    if ( !bridge.initialized ) return;
    if ( bridge.numEvents >= BRIDGE_MAX_EVENTS_PER_FRAME ) return;

    Com_Memcpy( &bridge.events[bridge.numEvents], event, sizeof(bridge_event_t) );
    bridge.numEvents++;
}

/*
==================
SV_BridgeRefreshActiveClients

Emit every active client (bot or human) EVERY server frame, reading fresh
kinematics straight from playerState_t (updated this frame by SV_ClientThink).

The QVM only pushes entities via BOTLIB_UPDATENTITY at its fixed bot-think rate
(~10 Hz regardless of sv_fps / bot_thinktime — measured), which caps the Python
observation rate at 10 Hz per bot. This function bypasses that path for the
kinematic fields the training loop needs (origin/velocity/viewangles/health),
giving sv_fps-rate observations for all clients. QVM-supplied static fields
(mins/maxs, anims, modelindex) persist in bridge.entities[] between the QVM's
10 Hz updates (the array is never zeroed per frame). Purely functional — reads
existing state, no gameplay/physics/think change. Gated by bridge_fullstate.
==================
*/
static void SV_BridgeRefreshActiveClients( void ) {
    int i;

    if ( !sv_maxclients || !sv.gameClients ) return;

    for ( i = 0; i < sv_maxclients->integer; i++ ) {
        bridge_entity_t *b;
        playerState_t *ps;

        if ( svs.clients[i].state != CS_ACTIVE ) continue;
        ps = SV_GameClientNum( i );
        if ( !ps ) continue;

        b = &bridge.entities[i];
        VectorCopy( ps->origin, b->base.origin );       // fresh position (sv_fps)
        VectorCopy( ps->velocity, b->velocity );
        VectorCopy( ps->viewangles, b->viewangles );
        b->health         = ps->stats[0];               // STAT_HEALTH
        b->armor          = ps->stats[3];               // STAT_ARMOR
        b->clientNum      = i;
        b->base.groundent = ps->groundEntityNum;
        b->base.weapon    = ps->weapon;
        b->ammo = ( ps->weapon >= 0 && ps->weapon < MAX_WEAPONS ) ? ps->ammo[ps->weapon] : 0;
        if ( b->base.type == 0 ) b->base.type = 1;      // ET_PLAYER (so obs/viz recognise it)

        bridge.entityUpdated[i] = qtrue;                // include in this frame's emit
        if ( i >= bridge.numEntities ) bridge.numEntities = i + 1;
    }
}

void SV_BridgeFrame( int serverTime ) {
    static char sendBuf[BRIDGE_BUFFER_SIZE * 4];
    int len = 0;
    int i;
    flatcc_builder_t *B;
    UrtBridge_Entity_vec_ref_t entsRef;
    UrtBridge_Event_vec_ref_t evsRef;
    UrtBridge_State_ref_t stRef;

    if ( !bridge.initialized ) return;

    // Accept new connections
    Bridge_AcceptClients();

    // Receive data from Python clients
    Bridge_ReceiveData();

    // Emit all active clients at sv_fps (independent of the QVM's ~10 Hz push)
    if ( bridge.fullstate && bridge.fullstate->integer ) {
        SV_BridgeRefreshActiveClients();
    }

    // If no clients connected, skip building the state
    if ( bridge.numClients == 0 ) goto cleanup;

    // Build the State FlatBuffer (mirror of the old JSON; sensors computed per entity).
    B = Bridge_Builder();
    UrtBridge_Entity_vec_start( B );
    for ( i = 0; i < bridge.numEntities; i++ ) {
        bridge_entity_t *ent;
        float rays[BRIDGE_SENSOR_N_RAY], ground, ceiling;
        int slick;

        if ( !bridge.entityUpdated[i] ) continue;
        ent = &bridge.entities[i];
        Bridge_ComputeSensors( ent, rays, &ground, &ceiling, &slick );

        UrtBridge_Entity_start( B );
        UrtBridge_Entity_id_add( B, i );
        UrtBridge_Entity_ent_type_add( B, ent->base.type );
        UrtBridge_Entity_flags_add( B, ent->base.flags );
        UrtBridge_Entity_origin_create( B, ent->base.origin[0], ent->base.origin[1], ent->base.origin[2] );
        UrtBridge_Entity_velocity_create( B, ent->velocity[0], ent->velocity[1], ent->velocity[2] );
        UrtBridge_Entity_angles_create( B, ent->base.angles[0], ent->base.angles[1], ent->base.angles[2] );
        UrtBridge_Entity_viewangles_create( B, ent->viewangles[0], ent->viewangles[1], ent->viewangles[2] );
        UrtBridge_Entity_health_add( B, ent->health );
        UrtBridge_Entity_armor_add( B, ent->armor );
        UrtBridge_Entity_weapon_add( B, ent->base.weapon );
        UrtBridge_Entity_ammo_add( B, ent->ammo );
        UrtBridge_Entity_client_num_add( B, ent->clientNum );
        UrtBridge_Entity_groundent_add( B, ent->base.groundent );
        UrtBridge_Entity_event_add( B, ent->base.event );
        UrtBridge_Entity_event_parm_add( B, ent->base.eventParm );
        UrtBridge_Entity_powerups_add( B, ent->base.powerups );
        UrtBridge_Entity_modelindex_add( B, ent->base.modelindex );
        UrtBridge_Entity_modelindex2_add( B, ent->base.modelindex2 );
        UrtBridge_Entity_legs_anim_add( B, ent->base.legsAnim );
        UrtBridge_Entity_torso_anim_add( B, ent->base.torsoAnim );
        UrtBridge_Entity_rays_add( B, flatbuffers_float_vec_create( B, rays, BRIDGE_SENSOR_N_RAY ) );
        UrtBridge_Entity_ground_add( B, ground );
        UrtBridge_Entity_ceiling_add( B, ceiling );
        UrtBridge_Entity_slick_add( B, slick );
        UrtBridge_Entity_vec_push( B, UrtBridge_Entity_end( B ) );
    }
    entsRef = UrtBridge_Entity_vec_end( B );

    UrtBridge_Event_vec_start( B );
    for ( i = 0; i < bridge.numEvents; i++ ) {
        bridge_event_t *ev = &bridge.events[i];
        UrtBridge_Event_start( B );
        UrtBridge_Event_event_type_add( B, ev->type );
        UrtBridge_Event_time_add( B, ev->serverTime );
        UrtBridge_Event_ent_add( B, ev->entityNum );
        UrtBridge_Event_other_add( B, ev->otherEntityNum );
        UrtBridge_Event_value_add( B, ev->value );
        UrtBridge_Event_origin_create( B, ev->origin[0], ev->origin[1], ev->origin[2] );
        UrtBridge_Event_vec_push( B, UrtBridge_Event_end( B ) );
    }
    evsRef = UrtBridge_Event_vec_end( B );

    UrtBridge_State_start( B );
    UrtBridge_State_time_add( B, serverTime );
    UrtBridge_State_mapname_add( B, flatbuffers_string_create_str( B, sv_mapname->string ) );
    UrtBridge_State_entities_add( B, entsRef );
    UrtBridge_State_events_add( B, evsRef );
    stRef = UrtBridge_State_end( B );
    UrtBridge_Message_create_as_root( B, UrtBridge_Payload_as_State( stRef ) );

    // Send to MONITOR clients only — AI clients are send-only and never read the
    // state (obs come from the single monitor connection). See Bridge_SendToMonitors.
    len = Bridge_FrameBuffer( B, sendBuf, sizeof( sendBuf ) );
    if ( len > 0 ) Bridge_SendToMonitors( sendBuf, len );

cleanup:
    // Reset per-frame state
    if ( bridge.entityUpdated ) {
        Com_Memset( bridge.entityUpdated, 0, BRIDGE_MAX_ENTITIES * sizeof(qboolean) );
    }
    bridge.numEntities = 0;
    bridge.numEvents = 0;
}

// Flag per client: bridge already called SV_ClientThink this frame
qboolean bridgeBotProcessed[MAX_CLIENTS];

static int bridgeDebugCounter = 0;

void SV_BridgeApplyBotCommands( void ) {
    int i;

    if ( !bridge.initialized ) return;

    // --- Latency fix: drain incoming commands HERE (start of the frame, right
    // before applying them) instead of only in SV_BridgeFrame (end of the frame,
    // after the QVM think). Without this, a command that arrives during frame F is
    // only cached at frame F's end and applied at frame F+1's start — and since
    // Python computes it from the state emitted at F's end, it lands one frame
    // later still, costing ~1 extra frame of action->effect round-trip.
    // Purely functional: fresher usercmd, no change to think sequencing or physics
    // (the bot still gets exactly one usercmd per frame). Client sockets are
    // non-blocking, so this returns immediately when nothing is pending, and the
    // later Bridge_ReceiveData() in SV_BridgeFrame still handles accept/monitor.
    Bridge_ReceiveData();

    // Reset processed flags at start of frame
    Com_Memset( bridgeBotProcessed, 0, sizeof(bridgeBotProcessed) );

    bridgeDebugCounter++;

    for ( i = 0; i < sv_maxclients->integer; i++ ) {
        bridge_bot_cmd_t *cmd;
        playerState_t *ps;
        usercmd_t ucmd;
        float yaw_rad, cos_yaw, sin_yaw;
        float fwd_dot, right_dot, speed_scale;

        if ( !bridge.botCmdValid[i] ) continue;

        // Verify this client slot is active
        if ( svs.clients[i].state != CS_ACTIVE ) {
            if ( bridgeDebugCounter % 200 == 1 ) {
                Com_DPrintf( "Bridge DEBUG: bot %d has cmd but state=%d (not ACTIVE)\n",
                    i, svs.clients[i].state );
            }
            continue;
        }

        cmd = &bridge.botCmds[i];
        ps = SV_GameClientNum( i );
        if ( !ps ) continue;

        // --- Respawn request ---
        // Python AI signals a stuck/stray bot: execute "kill" so the QVM
        // handles suicide + respawn to a spawn point, then skip this frame.
        if ( cmd->respawn ) {
            Com_DPrintf( "Bridge: respawning bot %d (kill command)\n", i );
            SV_ExecuteClientCommand( &svs.clients[i], "kill" );
            bridge.botCmdValid[i] = qfalse;
            cmd->respawn = 0;
            continue;
        }

        // Build usercmd_t directly — bypasses the entire EA/QVM bot AI pipeline
        Com_Memset( &ucmd, 0, sizeof(ucmd) );
        ucmd.serverTime = sv.time;

        // --- View angles ---
        // usercmd.angles = ANGLE2SHORT(desired) - ps->delta_angles
        ucmd.angles[0] = ANGLE2SHORT( cmd->viewAngles[0] ) - ps->delta_angles[0];
        ucmd.angles[1] = ANGLE2SHORT( cmd->viewAngles[1] ) - ps->delta_angles[1];
        ucmd.angles[2] = ANGLE2SHORT( cmd->viewAngles[2] ) - ps->delta_angles[2];

        // --- Movement ---
        // Convert world-space moveDir to player-relative forward/right
        yaw_rad = (float)( cmd->viewAngles[1] * M_PI / 180.0 );
        cos_yaw = (float)cos( yaw_rad );
        sin_yaw = (float)sin( yaw_rad );

        // Player's forward vector: [cos(yaw), sin(yaw)]
        // Player's right vector:   [sin(yaw), -cos(yaw)]
        fwd_dot   = cmd->moveDir[0] * cos_yaw + cmd->moveDir[1] * sin_yaw;
        right_dot = cmd->moveDir[0] * sin_yaw - cmd->moveDir[1] * cos_yaw;

        speed_scale = cmd->moveSpeed / 127.0f;
        if ( speed_scale > 1.0f ) speed_scale = 1.0f;

        ucmd.forwardmove = (signed char)( fwd_dot * speed_scale * 127.0f );
        ucmd.rightmove   = (signed char)( right_dot * speed_scale * 127.0f );

        // --- Vertical movement ---
        if ( cmd->jump )        ucmd.upmove = 127;
        else if ( cmd->crouch ) ucmd.upmove = -127;

        // --- Buttons ---
        if ( cmd->attack )  ucmd.buttons |= BUTTON_ATTACK;
        // BUTTON_SPRINT is a QVM/game button (q_shared.h in the mod: 1<<8) that the
        // engine's own q_shared.h does not define; the value is passed through
        // verbatim to the game VM. Sprint raises the ground/ice wishspeed to
        // UT_MAX_SPRINTSPEED (340) and switches PM_WalkMove to the faster accel
        // branch (pm_friction+0.05) -- the ice acceleration regime. Purely an input
        // passthrough: no physics/gameplay/think change (cf. attack/jump above).
        // NB the QVM only honours sprint when rightmove==0 && forwardmove>80.
        if ( cmd->sprint )  ucmd.buttons |= 256; /* BUTTON_SPRINT (1<<8) */

        // --- Weapon ---
        ucmd.weapon = (byte)( cmd->weapon ? cmd->weapon : ps->weapon );

        // Debug logging (every 200 frames for bot 0)
        if ( i == 0 && bridgeDebugCounter % 200 == 1 ) {
            Com_DPrintf( "Bridge DEBUG: bot %d cmd fwd=%d right=%d up=%d "
                "svtime=%d cmdtime=%d pos=(%.0f,%.0f,%.0f) vel=(%.0f,%.0f,%.0f)\n",
                i, ucmd.forwardmove, ucmd.rightmove, ucmd.upmove,
                sv.time, ps->commandTime,
                ps->origin[0], ps->origin[1], ps->origin[2],
                ps->velocity[0], ps->velocity[1], ps->velocity[2] );
        }

        // Inject the command directly into the engine
        SV_ClientThink( &svs.clients[i], &ucmd );
        bridgeBotProcessed[i] = qtrue;
    }
}

qboolean SV_BridgeControlsBot( int clientNum ) {
    int i;

    if ( !bridge.initialized ) return qfalse;

    for ( i = 0; i < BRIDGE_MAX_CLIENTS; i++ ) {
        if ( bridge.clients[i].active && bridge.clients[i].isAI &&
             bridge.clients[i].controlledBot == clientNum ) {
            return qtrue;
        }
    }
    return qfalse;
}
